--PREM*
USE [master]---hgf-ds-hgfd
GO
/****** Object:  Database [DannySSIS]    Script Date: 01-10-2021 19:04:39 ******/
CREATE DATABASE [DannySSIS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DannySSIS', FILENAME = N'F:\Danny DB files\DannySSIS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DannySSIS_log', FILENAME = N'F:\Danny DB files\DannySSIS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DannySSIS] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DannySSIS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DannySSIS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DannySSIS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DannySSIS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DannySSIS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DannySSIS] SET ARITHABORT OFF 
GO
ALTER DATABASE [DannySSIS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DannySSIS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DannySSIS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DannySSIS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DannySSIS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DannySSIS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DannySSIS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DannySSIS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DannySSIS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DannySSIS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DannySSIS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DannySSIS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DannySSIS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DannySSIS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DannySSIS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DannySSIS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DannySSIS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DannySSIS] SET RECOVERY FULL 
GO
ALTER DATABASE [DannySSIS] SET  MULTI_USER 
GO
ALTER DATABASE [DannySSIS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DannySSIS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DannySSIS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DannySSIS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DannySSIS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DannySSIS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DannySSIS', N'ON'
GO
ALTER DATABASE [DannySSIS] SET QUERY_STORE = OFF
GO
USE [DannySSIS]
GO
/****** Object:  Table [dbo].[DimCountry]    Script Date: 01-10-2021 19:04:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimCountry](
	[CountryId] [int] NOT NULL,
	[CountryName] [nvarchar](50) NULL,
	[IsNew] [bit] NULL,
	[Create_Date] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimProduct]    Script Date: 01-10-2021 19:04:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimProduct](
	[ProductId] [int] NOT NULL,
	[ProductName] [nvarchar](50) NULL,
	[DateCreated] [datetime] NULL,
	[DateExpired] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimSalesPerson]    Script Date: 01-10-2021 19:04:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimSalesPerson](
	[SalesPersonId] [int] NOT NULL,
	[SalesPersonName] [nvarchar](50) NULL,
 CONSTRAINT [PK_DimSalesPerson] PRIMARY KEY CLUSTERED 
(
	[SalesPersonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimStates]    Script Date: 01-10-2021 19:04:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimStates](
	[StatesId] [int] NOT NULL,
	[StatesName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DimStates] PRIMARY KEY CLUSTERED 
(
	[StatesId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FactCustomer]    Script Date: 01-10-2021 19:04:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactCustomer](
	[CustID] [nvarchar](50) NOT NULL,
	[CustName] [nvarchar](50) NULL,
	[SalesAmount] [money] NULL,
	[SaleDate] [datetime] NULL,
	[CountryId_Fk] [int] NULL,
	[StatesId_Fk] [int] NULL,
	[ProductId_Fk] [int] NULL,
	[SalesPersonId_Fk] [int] NULL,
 CONSTRAINT [PK_CustomerDetails] PRIMARY KEY CLUSTERED 
(
	[CustID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DimCountry] ADD  DEFAULT (getdate()) FOR [Create_Date]
GO
ALTER TABLE [dbo].[FactCustomer]  WITH NOCHECK ADD  CONSTRAINT [FK_FactCustomer_DimSalesPerson] FOREIGN KEY([SalesPersonId_Fk])
REFERENCES [dbo].[DimSalesPerson] ([SalesPersonId])
GO
ALTER TABLE [dbo].[FactCustomer] CHECK CONSTRAINT [FK_FactCustomer_DimSalesPerson]
GO
ALTER TABLE [dbo].[FactCustomer]  WITH NOCHECK ADD  CONSTRAINT [FK_FactCustomer_DimStates] FOREIGN KEY([SalesPersonId_Fk])
REFERENCES [dbo].[DimStates] ([StatesId])
GO
ALTER TABLE [dbo].[FactCustomer] CHECK CONSTRAINT [FK_FactCustomer_DimStates]
GO
USE [master]
GO
ALTER DATABASE [DannySSIS] SET  READ_WRITE 
GO
